"""Containerisation, generated from measured facts rather than guessed.

Every line of the produced Dockerfile is a consequence of something already
established by an earlier stage:

* the interpreter version is the one the lockfile was compiled against, because
  a lock resolved under one version can install differently under another
  (environment markers such as ``tomli; python_version<"3.11"``);
* the install steps are the two verified against a clean environment;
* the test command is the one the hygiene stage already runs.

Correctness is decided by execution: build, run the suite twice, and require the
two runs to agree with each other *and* with the host baseline.
"""

from __future__ import annotations

import re
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from stress_stack.tooling import run

_CANDIDATE_PYTHONS = ("3.12", "3.11", "3.10", "3.9")
_DEFAULT_PYTHON = "3.12"
_SPECIFIER = re.compile(r"(==|!=|>=|<=|~=|>|<)\s*([0-9][0-9.*]*)")

_DOCKERIGNORE = """\
# Generated by stress-stack. Keeps the build context small and stable —
# .stress_stack/ holds tool virtual environments and would otherwise make the
# context large and different on every run.
.stress_stack/
.git/
.venv/
venv/
__pycache__/
*.py[cod]
.pytest_cache/
.ruff_cache/
.mypy_cache/
.tox/
build/
dist/
*.egg-info/
"""


@dataclass(frozen=True, slots=True)
class ContainerResult:
    dockerfile: Path
    image: str
    python_version: str
    base_image: str
    build_status: str
    build_seconds: float
    build_log_tail: str
    runs: list[dict[str, Any]]
    identical: bool
    baseline_match: str
    status: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": "0.1.0",
            "status": self.status,
            "image": self.image,
            "python_version": self.python_version,
            "base_image": self.base_image,
            "build": {
                "status": self.build_status,
                "seconds": self.build_seconds,
                "log_tail": self.build_log_tail,
            },
            "runs": self.runs,
            "runs_identical": self.identical,
            "baseline_match": self.baseline_match,
        }


def select_python_version(requires_python: str | None) -> str:
    """Newest candidate interpreter the project's ``requires-python`` allows."""
    if not requires_python:
        return _DEFAULT_PYTHON
    for candidate in _CANDIDATE_PYTHONS:
        if _satisfies(candidate, requires_python):
            return candidate
    return _DEFAULT_PYTHON


def _satisfies(version: str, specifier: str) -> bool:
    parsed = _version_tuple(version)
    for operator, raw in _SPECIFIER.findall(specifier):
        if raw.endswith(".*"):
            raw = raw[:-2]
        bound = _version_tuple(raw)
        width = min(len(parsed), len(bound)) or 1
        left, right = parsed[:width], bound[:width]
        if operator == ">=" and not left >= right:
            return False
        if operator == ">" and not left > right:
            return False
        if operator == "<=" and not left <= right:
            return False
        if operator == "<" and not _version_tuple(version)[: len(bound)] < bound:
            return False
        if operator == "==" and left != right:
            return False
        if operator == "!=" and left == right:
            return False
        if operator == "~=" and not left >= right:
            return False
    return True


def _version_tuple(value: str) -> tuple[int, ...]:
    parts: list[int] = []
    for chunk in value.split("."):
        if chunk.isdigit():
            parts.append(int(chunk))
        else:
            break
    return tuple(parts) or (0,)


def pin_image_by_digest(tag: str) -> tuple[str, str]:
    """Resolve any registry tag to an immutable digest reference.

    Tags move; digests do not. Every ecosystem's base image needs this, not just
    Python's, so the logic lives here and takes the tag as an argument rather
    than deriving it from an interpreter version.
    """
    # Public base images do not need credentials. A broken desktop keychain
    # helper should not prevent a reproducible pull, so use an isolated empty
    # Docker config for this one public registry operation.
    with tempfile.TemporaryDirectory(prefix="stress-stack-docker-") as directory:
        config = Path(directory)
        (config / "config.json").write_text("{}\n", encoding="utf-8")
        pull = run(
            ["docker", "--config", str(config), "pull", "--quiet", tag],
            timeout=900.0,
        )
    inspect = run(
        ["docker", "image", "inspect", tag, "--format", "{{index .RepoDigests 0}}"],
        timeout=120.0,
    )
    digest = inspect.stdout.strip()
    if inspect.ok and "@sha256:" in digest:
        return digest, "digest_pinned" if pull.ok else "digest_pinned_cached"
    return tag, "tag_unpinned_no_digest" if pull.ok else "tag_unpinned_pull_failed"


def resolve_base_image(python_version: str) -> tuple[str, str]:
    """Pin the Python base by digest, falling back to the minor-version tag."""
    tag = f"python:{python_version}-slim"
    reference, status = pin_image_by_digest(tag)
    if status.startswith("digest_pinned"):
        return reference, status
    pull_ok = not status.endswith("pull_failed")
    if python_version.count(".") == 2:
        minor_tag = f"python:{python_version.rsplit('.', 1)[0]}-slim"
        cached = run(
            ["docker", "image", "inspect", minor_tag, "--format", "{{index .RepoDigests 0}}"],
            timeout=120.0,
        )
        cached_digest = cached.stdout.strip()
        if cached.ok and "@sha256:" in cached_digest:
            return cached_digest, "digest_pinned_cached_patch_fallback"
    return tag, "tag_unpinned_no_digest" if pull_ok else "tag_unpinned_pull_failed"


_PYTEST_REQUIREMENT = "pytest>=8,<9"

# The directory testgen writes into. Its contents are this pipeline's output,
# not the repository's suite, and they are regenerated between the host baseline
# and the image.
_GENERATED_MARKER = "stress_stack_generated"


def render_dockerfile(
    base_image: str,
    *,
    has_lock: bool,
    installable: bool,
    test_command: str,
    has_runner: bool = True,
    project_name: str | None = None,
    project_version: str | None = None,
) -> str:
    lines = ["# Generated by stress-stack."]
    if has_lock:
        lines += [
            "# The interpreter matches the version the lockfile was compiled for;",
            "# installing that lock under a different version can resolve differently.",
        ]
    lines += [
        f"FROM {base_image}",
        "",
        "ENV PYTHONDONTWRITEBYTECODE=1 \\",
        "    PYTHONUNBUFFERED=1 \\",
        "    PYTHONHASHSEED=0 \\",
        "    PIP_NO_CACHE_DIR=1 \\",
        "    PIP_DISABLE_PIP_VERSION_CHECK=1",
        "",
        "WORKDIR /app",
        "",
        # Common Unix programs are part of observable CLI behavior for many
        # Python projects. In particular, pager tests set PAGER=less and a slim
        # image otherwise changes 24 Click outcomes compared with the host.
        "RUN apt-get update && apt-get install -y --no-install-recommends git less \\",
        "    && rm -rf /var/lib/apt/lists/*",
        "",
    ]
    if has_lock:
        lines += [
            "# Dependencies first: this layer only changes when the lock changes.",
            "COPY requirements.lock ./requirements.lock",
            "RUN pip install --require-hashes --no-deps -r requirements.lock",
            "",
        ]
    if not has_runner:
        lines += [
            "# Manifestless fallback only. Manifest-backed locks include the runner.",
            f'RUN pip install "{_PYTEST_REQUIREMENT}"',  # quoted: > and < redirect in sh
            "",
        ]
    lines += ["COPY . .", ""]
    if installable:
        if project_version and re.fullmatch(r"[A-Za-z0-9.+!_-]+", project_version):
            lines += [
                "# SCM-backed builds need a version after .git is excluded.",
                f"ENV SETUPTOOLS_SCM_PRETEND_VERSION={project_version}",
            ]
            if project_name:
                normalized = re.sub(r"[^A-Za-z0-9]", "_", project_name).upper()
                lines.append(
                    f"ENV SETUPTOOLS_SCM_PRETEND_VERSION_FOR_{normalized}={project_version}"
                )
            lines.append("")
        lines += [
            "# Dependencies are already pinned above; install the project alone so",
            "# console entry points exist without re-resolving anything.",
            "RUN pip install --no-deps --no-build-isolation .",
            "",
        ]
    lines += [f"CMD {test_command}", ""]
    return "\n".join(lines)


def build_image(root: Path, image: str) -> tuple[str, float, str]:
    start = time.monotonic()
    result = run(
        ["docker", "build", "--tag", image, "--file", "Dockerfile", "."],
        cwd=root,
        timeout=1800.0,
    )
    duration = round(time.monotonic() - start, 2)
    log = (result.stdout + result.stderr).strip().splitlines()
    return ("built" if result.ok else "failed"), duration, "\n".join(log[-12:])


def run_suite_in_container(image: str, evidence: Path, name: str) -> dict[str, Any]:
    """Run the suite inside the image, writing a JUnit report to the host."""
    evidence.mkdir(parents=True, exist_ok=True)
    report = evidence / f"{name}.xml"
    report.unlink(missing_ok=True)
    start = time.monotonic()
    result = run(
        [
            "docker",
            "run",
            "--rm",
            "--network",
            "none",
            "--volume",
            f"{evidence}:/evidence",
            image,
            "python",
            "-m",
            "pytest",
            "-p",
            "no:cacheprovider",
            "--tb=no",
            "-q",
            f"--junit-xml=/evidence/{name}.xml",
        ],
        timeout=1800.0,
    )
    from stress_stack.pytest_runner import _parse_report

    outcomes = _parse_report(report)
    return {
        "name": name,
        "exit_code": result.exit_code,
        "seconds": round(time.monotonic() - start, 2),
        "total": len(outcomes),
        "passed": sum(1 for value in outcomes.values() if value == "passed"),
        "failed": sum(1 for value in outcomes.values() if value in {"failed", "error"}),
        "outcomes": dict(sorted(outcomes.items())),
        "log_tail": "\n".join((result.stdout + result.stderr).strip().splitlines()[-6:]),
    }


def compare_to_baseline(outcomes: dict[str, str], baseline: dict[str, str] | None) -> str:
    if not baseline:
        return "no_baseline"
    if not outcomes:
        return "container_produced_no_results"
    # A test the container ran and the host baseline never saw is an addition,
    # not a disagreement. Test generation runs before containerization and adds
    # files to the suite on purpose, so demanding set equality here made a
    # successful generation stage look like a broken image. A test the *host*
    # ran and the container did not is the real fault: something failed to
    # collect.
    # Tests this pipeline generated are not part of the repository's suite, and
    # testgen rewrites them wholesale between the baseline and the image. On a
    # re-run against a tree that still holds the previous run's generated files,
    # a regenerated test disappearing from the baseline is the generator working,
    # not the image failing to collect. A fresh clone never sees this, which is
    # why it survived the first glom run.
    disappeared = {
        test for test in set(baseline) - set(outcomes) if _GENERATED_MARKER not in test
    }
    if disappeared:
        return "tests_missing_in_container"
    # A platform-specific skip becoming a pass is harmless. A host pass
    # becoming anything else is a regression. Container acceptance separately
    # requires exit zero and no failures, so this rule cannot bless a stable
    # failing suite.
    regressions = {
        key
        for key, value in baseline.items()
        if value == "passed"
        and outcomes.get(key) != "passed"
        and _GENERATED_MARKER not in key
    }
    if regressions:
        return "differs"
    return "matches_with_additions" if set(outcomes) - set(baseline) else "matches"


def interpreter_version(python: Path) -> str | None:
    """Return the exact provisioned interpreter version for image parity."""
    result = run(
        [str(python), "-c", "import platform; print(platform.python_version())"],
        timeout=30.0,
    )
    value = result.stdout.strip()
    return value if result.ok and re.fullmatch(r"\d+\.\d+\.\d+", value) else None


def detect_missing_system_library(build_log: str) -> str | None:
    """Name the missing header when a source build fails, or admit we cannot.

    Guessing an apt package here would look like a fix while changing nothing,
    so an unrecognised failure is reported rather than invented.
    """
    header = re.search(r"fatal error: ([\w./+-]+\.h)", build_log)
    if header:
        return header.group(1)
    if "error: command '" in build_log and "failed with exit" in build_log:
        return "unknown_compiler_failure"
    return None
