"""Containerisation, generated from measured facts rather than guessed.

Every line of the produced Dockerfile is a consequence of something already
established by an earlier stage:

* the interpreter version is the one the lockfile was compiled against, because
  a lock resolved under one version can install differently under another
  (environment markers such as ``tomli; python_version<"3.11"``);
* the install steps are the two verified against a clean environment;
* the test command is the one the hygiene stage already runs.

Correctness is decided by execution: build, run the suite twice, and require the
two runs to agree with each other *and* with the host baseline.
"""

from __future__ import annotations

import re
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from stress_stack.tooling import run

_CANDIDATE_PYTHONS = ("3.12", "3.11", "3.10", "3.9")
_DEFAULT_PYTHON = "3.12"
_SPECIFIER = re.compile(r"(==|!=|>=|<=|~=|>|<)\s*([0-9][0-9.*]*)")

_DOCKERIGNORE = """\
# Generated by stress-stack. Keeps the build context small and stable —
# .stress_stack/ holds tool virtual environments and would otherwise make the
# context large and different on every run.
.stress_stack/
.git/
.venv/
venv/
__pycache__/
*.py[cod]
.pytest_cache/
.ruff_cache/
.mypy_cache/
.tox/
build/
dist/
*.egg-info/
"""


@dataclass(frozen=True, slots=True)
class ContainerResult:
    dockerfile: Path
    image: str
    python_version: str
    base_image: str
    build_status: str
    build_seconds: float
    build_log_tail: str
    runs: list[dict[str, Any]]
    identical: bool
    baseline_match: str
    status: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": "0.1.0",
            "status": self.status,
            "image": self.image,
            "python_version": self.python_version,
            "base_image": self.base_image,
            "build": {
                "status": self.build_status,
                "seconds": self.build_seconds,
                "log_tail": self.build_log_tail,
            },
            "runs": self.runs,
            "runs_identical": self.identical,
            "baseline_match": self.baseline_match,
        }


def select_python_version(requires_python: str | None) -> str:
    """Newest candidate interpreter the project's ``requires-python`` allows."""
    if not requires_python:
        return _DEFAULT_PYTHON
    for candidate in _CANDIDATE_PYTHONS:
        if _satisfies(candidate, requires_python):
            return candidate
    return _DEFAULT_PYTHON


def _satisfies(version: str, specifier: str) -> bool:
    parsed = _version_tuple(version)
    for operator, raw in _SPECIFIER.findall(specifier):
        if raw.endswith(".*"):
            raw = raw[:-2]
        bound = _version_tuple(raw)
        width = min(len(parsed), len(bound)) or 1
        left, right = parsed[:width], bound[:width]
        if operator == ">=" and not left >= right:
            return False
        if operator == ">" and not left > right:
            return False
        if operator == "<=" and not left <= right:
            return False
        if operator == "<" and not _version_tuple(version)[: len(bound)] < bound:
            return False
        if operator == "==" and left != right:
            return False
        if operator == "!=" and left == right:
            return False
        if operator == "~=" and not left >= right:
            return False
    return True


def _version_tuple(value: str) -> tuple[int, ...]:
    parts: list[int] = []
    for chunk in value.split("."):
        if chunk.isdigit():
            parts.append(int(chunk))
        else:
            break
    return tuple(parts) or (0,)


def resolve_base_image(python_version: str) -> tuple[str, str]:
    """Pin the base by digest when we can — tags move, digests do not."""
    tag = f"python:{python_version}-slim"
    pull = run(["docker", "pull", "--quiet", tag], timeout=900.0)
    if not pull.ok:
        return tag, "tag_unpinned_pull_failed"
    inspect = run(
        ["docker", "image", "inspect", tag, "--format", "{{index .RepoDigests 0}}"],
        timeout=120.0,
    )
    digest = inspect.stdout.strip()
    if inspect.ok and "@sha256:" in digest:
        return digest, "digest_pinned"
    return tag, "tag_unpinned_no_digest"


_PYTEST_REQUIREMENT = "pytest>=8,<9"


def render_dockerfile(
    base_image: str,
    *,
    has_lock: bool,
    installable: bool,
    test_command: str,
    has_runner: bool = True,
) -> str:
    lines = ["# Generated by stress-stack."]
    if has_lock:
        lines += [
            "# The interpreter matches the version the lockfile was compiled for;",
            "# installing that lock under a different version can resolve differently.",
        ]
    lines += [
        f"FROM {base_image}",
        "",
        "ENV PYTHONDONTWRITEBYTECODE=1 \\",
        "    PYTHONUNBUFFERED=1 \\",
        "    PYTHONHASHSEED=0 \\",
        "    PIP_NO_CACHE_DIR=1 \\",
        "    PIP_DISABLE_PIP_VERSION_CHECK=1",
        "",
        "WORKDIR /app",
        "",
    ]
    if has_lock:
        lines += [
            "# Dependencies first: this layer only changes when the lock changes.",
            "COPY requirements.lock ./requirements.lock",
            "RUN pip install --require-hashes --no-deps -r requirements.lock",
            "",
        ]
    if not has_runner:
        lines += [
            "# The harness needs a runner even when the repository does not",
            "# declare one as an installable extra. click states its test",
            "# dependencies under PEP 735 [dependency-groups], so the compiled",
            "# lock held nothing and the image had no pytest — every run then",
            "# exited non-zero having collected nothing.",
            f'RUN pip install "{_PYTEST_REQUIREMENT}"',  # quoted: > and < redirect in sh
            "",
        ]
    lines += ["COPY . .", ""]
    if installable:
        lines += [
            "# Dependencies are already pinned above; install the project alone so",
            "# console entry points exist without re-resolving anything.",
            "RUN pip install --no-deps .",
            "",
        ]
    lines += [f"CMD {test_command}", ""]
    return "\n".join(lines)


def build_image(root: Path, image: str) -> tuple[str, float, str]:
    start = time.monotonic()
    result = run(
        ["docker", "build", "--tag", image, "--file", "Dockerfile", "."],
        cwd=root,
        timeout=1800.0,
    )
    duration = round(time.monotonic() - start, 2)
    log = (result.stdout + result.stderr).strip().splitlines()
    return ("built" if result.ok else "failed"), duration, "\n".join(log[-12:])


def run_suite_in_container(image: str, evidence: Path, name: str) -> dict[str, Any]:
    """Run the suite inside the image, writing a JUnit report to the host."""
    evidence.mkdir(parents=True, exist_ok=True)
    report = evidence / f"{name}.xml"
    report.unlink(missing_ok=True)
    start = time.monotonic()
    result = run(
        [
            "docker",
            "run",
            "--rm",
            "--network",
            "none",
            "--volume",
            f"{evidence}:/evidence",
            image,
            "python",
            "-m",
            "pytest",
            "-p",
            "no:cacheprovider",
            "--tb=no",
            "-q",
            f"--junit-xml=/evidence/{name}.xml",
        ],
        timeout=1800.0,
    )
    from stress_stack.pytest_runner import _parse_report

    outcomes = _parse_report(report)
    return {
        "name": name,
        "exit_code": result.exit_code,
        "seconds": round(time.monotonic() - start, 2),
        "total": len(outcomes),
        "passed": sum(1 for value in outcomes.values() if value == "passed"),
        "outcomes": dict(sorted(outcomes.items())),
        "log_tail": "\n".join((result.stdout + result.stderr).strip().splitlines()[-6:]),
    }


def compare_to_baseline(outcomes: dict[str, str], baseline: dict[str, str] | None) -> str:
    if not baseline:
        return "no_baseline"
    if not outcomes:
        return "container_produced_no_results"
    baseline_pass = {key for key, value in baseline.items() if value == "passed"}
    container_pass = {key for key, value in outcomes.items() if value == "passed"}
    if baseline_pass == container_pass:
        return "matches"
    if len(baseline_pass) == len(container_pass):
        return "same_count_different_ids"
    return "differs"


def detect_missing_system_library(build_log: str) -> str | None:
    """Name the missing header when a source build fails, or admit we cannot.

    Guessing an apt package here would look like a fix while changing nothing,
    so an unrecognised failure is reported rather than invented.
    """
    header = re.search(r"fatal error: ([\w./+-]+\.h)", build_log)
    if header:
        return header.group(1)
    if "error: command '" in build_log and "failed with exit" in build_log:
        return "unknown_compiler_failure"
    return None
