from __future__ import annotations

from stress_stack.container import (
    compare_to_baseline,
    detect_missing_system_library,
    render_dockerfile,
    select_python_version,
)


def test_python_version_follows_requires_python() -> None:
    assert select_python_version(">=3.12") == "3.12"
    assert select_python_version(">=3.8") == "3.12"
    assert select_python_version(">=3.8,<3.11") == "3.10"
    assert select_python_version("<3.10") == "3.9"
    assert select_python_version("==3.11") == "3.11"


def test_python_version_defaults_when_unspecified() -> None:
    """glom declares no python_requires at all, so a default is required."""
    assert select_python_version(None) == "3.12"
    assert select_python_version("") == "3.12"


def test_dockerfile_installs_lock_before_copying_source() -> None:
    content = render_dockerfile(
        "python@sha256:abc", has_lock=True, installable=True, test_command='["pytest"]'
    )
    lines = content.splitlines()
    lock_index = next(i for i, line in enumerate(lines) if "requirements.lock" in line)
    copy_index = next(i for i, line in enumerate(lines) if line == "COPY . .")

    assert lock_index < copy_index
    assert "--require-hashes" in content
    assert "RUN pip install --no-deps ." in content
    assert content.startswith("# Generated by stress-stack.")


def test_dockerfile_omits_steps_that_do_not_apply() -> None:
    content = render_dockerfile(
        "python:3.12-slim", has_lock=False, installable=False, test_command='["pytest"]'
    )

    assert "requirements.lock" not in content
    assert "pip install --no-deps ." not in content
    assert "COPY . ." in content


def test_dockerfile_sets_determinism_environment() -> None:
    content = render_dockerfile(
        "python@sha256:abc", has_lock=True, installable=True, test_command='["pytest"]'
    )

    for variable in ("PYTHONHASHSEED=0", "PYTHONDONTWRITEBYTECODE=1", "PIP_NO_CACHE_DIR=1"):
        assert variable in content


def test_baseline_comparison_distinguishes_failure_modes() -> None:
    baseline = {"a": "passed", "b": "passed", "c": "failed"}

    assert compare_to_baseline({"a": "passed", "b": "passed", "c": "failed"}, baseline) == "matches"
    assert compare_to_baseline({"a": "passed", "b": "failed", "c": "failed"}, baseline) == "differs"
    assert compare_to_baseline({}, baseline) == "container_produced_no_results"
    assert compare_to_baseline({"a": "passed"}, None) == "no_baseline"
    assert (
        compare_to_baseline({"x": "passed", "y": "passed", "c": "failed"}, baseline)
        == "same_count_different_ids"
    )


def test_missing_system_library_is_named_or_admitted() -> None:
    log = "  lxml/etree.c:96:10: fatal error: libxml/xmlversion.h: No such file"
    assert detect_missing_system_library(log) == "libxml/xmlversion.h"

    opaque = "error: command '/usr/bin/gcc' failed with exit code 1"
    assert detect_missing_system_library(opaque) == "unknown_compiler_failure"

    assert detect_missing_system_library("Successfully built wheel") is None
