from __future__ import annotations

from pathlib import Path

from stress_stack.locking import (
    compile_lock,
    count_packages,
    find_manifest,
    locked_packages,
    select_extras,
    test_dependency_group as dependency_group,
)
from stress_stack.tooling import CommandResult

_LOCK = """\
# This file was autogenerated by uv via the following command:
#    uv pip compile setup.py --extra test
attrs==26.1.0 \\
    --hash=sha256:c647aa4a12dfbad9333ca4e71fe62ddc36f4e63b2d260a37a8b83d2f043ac309
    # via glom (setup.py)
boltons==26.1.0
    # via
    #   glom (setup.py)
    #   face
pyyaml==6.0.3
    # via glom (setup.py)
"""


def test_finds_manifest_in_precedence_order(tmp_path: Path) -> None:
    assert find_manifest(tmp_path) is None

    (tmp_path / "setup.py").write_text("", encoding="utf-8")
    assert find_manifest(tmp_path) == "setup.py"

    (tmp_path / "pyproject.toml").write_text("", encoding="utf-8")
    assert find_manifest(tmp_path) == "pyproject.toml"


def test_parses_pins_ignoring_hashes_and_annotations(tmp_path: Path) -> None:
    lockfile = tmp_path / "requirements.lock"
    lockfile.write_text(_LOCK, encoding="utf-8")

    assert locked_packages(lockfile) == {
        "attrs": "26.1.0",
        "boltons": "26.1.0",
        "pyyaml": "6.0.3",
    }
    assert count_packages(lockfile) == 3


def test_missing_lockfile_parses_as_empty(tmp_path: Path) -> None:
    assert locked_packages(tmp_path / "absent.lock") == {}
    assert count_packages(tmp_path / "absent.lock") == 0


def test_selects_the_conventional_test_extra() -> None:
    assert select_extras(["toml", "yaml", "test"]) == ["test"]
    assert select_extras(["Dev", "docs"]) == ["Dev"]
    assert select_extras(["docs", "toml"]) == []
    assert select_extras([]) == []


def test_repository_without_a_manifest_is_skipped_not_failed(tmp_path: Path) -> None:
    result = compile_lock(tmp_path, tmp_path / "requirements.lock")

    assert result.status == "skipped"
    assert result.reason == "no_dependency_manifest_found"
    assert result.lockfile is None


def test_pep735_test_group_is_compiled_into_the_lock(monkeypatch, tmp_path: Path) -> None:
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname="demo"\nversion="1"\n[dependency-groups]\ntests=["pytest", "coverage"]\n',
        encoding="utf-8",
    )
    calls: list[list[str]] = []

    def fake_run(arguments, **kwargs):
        calls.append(list(arguments))
        destination = Path(arguments[arguments.index("-o") + 1])
        destination.write_text("pytest==8.4.0\ncoverage==7.10.0\n")
        return CommandResult(" ".join(arguments), 0, "", "")

    monkeypatch.setattr("stress_stack.locking.run", fake_run)
    result = compile_lock(tmp_path, tmp_path / "requirements.lock")

    assert dependency_group(tmp_path) == ("tests", ["pytest", "coverage"])
    assert result.groups == ["tests"]
    assert ["--group", "tests"] == calls[0][
        calls[0].index("--group") : calls[0].index("--group") + 2
    ]
    assert result.package_count == 2


def test_build_backend_is_compiled_into_the_same_lock(monkeypatch, tmp_path: Path) -> None:
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname="demo"\nversion="1"\n'
        '[build-system]\nrequires=["flit_core>=3.11,<4"]\nbuild-backend="flit_core.buildapi"\n',
        encoding="utf-8",
    )
    calls: list[list[str]] = []

    def fake_run(arguments, **kwargs):
        calls.append(list(arguments))
        destination = Path(arguments[arguments.index("-o") + 1])
        destination.write_text("flit-core==3.12.0\n", encoding="utf-8")
        return CommandResult(" ".join(arguments), 0, "", "")

    monkeypatch.setattr("stress_stack.locking.run", fake_run)
    result = compile_lock(tmp_path, tmp_path / "requirements.lock")

    build_input = tmp_path / ".stress_stack" / "locking" / "build-requirements.in"
    assert str(build_input) in calls[0]
    assert build_input.read_text(encoding="utf-8") == (
        "pytest>=8,<10\nflit_core>=3.11,<4\n"
    )
    assert result.package_count == 1
