from __future__ import annotations

import json
import tomllib
from pathlib import Path

from stress_stack.hygiene import (
    _baseline_configuration,
    _declared_extras,
    _rule_counts,
    _write_configuration,
)


def write_report(path: Path, root: Path, extras: list[str] | None) -> None:
    metadata: dict[str, object] = {"name": "example"}
    if extras is not None:
        metadata["provides_extra"] = extras
    path.write_text(
        json.dumps(
            {
                "install": [
                    {
                        "download_info": {"url": "https://pypi.org/simple/attrs"},
                        "metadata": {"name": "attrs", "provides_extra": ["dev"]},
                    },
                    {
                        "download_info": {"url": root.resolve().as_uri()},
                        "metadata": metadata,
                    },
                ]
            }
        ),
        encoding="utf-8",
    )


def test_declared_extras_reads_the_local_project_not_dependencies(tmp_path: Path) -> None:
    report = tmp_path / "report.json"
    write_report(report, tmp_path, ["toml", "yaml", "test"])

    assert _declared_extras(report, tmp_path) == ["toml", "yaml", "test"]


def test_declared_extras_handles_missing_and_malformed_reports(tmp_path: Path) -> None:
    assert _declared_extras(tmp_path / "absent.json", tmp_path) == []

    broken = tmp_path / "broken.json"
    broken.write_text("{not json", encoding="utf-8")
    assert _declared_extras(broken, tmp_path) == []

    without = tmp_path / "without.json"
    write_report(without, tmp_path, None)
    assert _declared_extras(without, tmp_path) == []


def test_baseline_configuration_is_valid_toml_with_every_residual_rule() -> None:
    content = _baseline_configuration(
        {"F401": 57, "E731": 19, "E722": 2},
        {"F401": "unused-import", "E731": "lambda-assignment"},
        78,
    )
    parsed = tomllib.loads(content)

    assert parsed["lint"]["ignore"] == ["E722", "E731", "F401"]
    assert parsed["extend-exclude"] == [".stress_stack"]


def test_baseline_configuration_records_count_date_and_rationale() -> None:
    content = _baseline_configuration({"F401": 57}, {"F401": "unused-import"}, 57)

    assert "Baseline adopted 20" in content
    assert "57 violation(s) across 1 rule(s)" in content
    assert "unsafe" in content.lower()
    assert "#   F401      57  unused-import" in content


def test_empty_residual_produces_empty_ignore_list() -> None:
    content = _baseline_configuration({}, {}, 0)
    assert tomllib.loads(content)["lint"]["ignore"] == []


def test_rule_counts_ignores_malformed_entries() -> None:
    counts = _rule_counts(
        [{"code": "F401"}, {"code": "F401"}, {"code": None}, {}, {"code": "E731"}]
    )
    assert counts == {"F401": 2, "E731": 1}


def test_existing_configuration_is_backed_up_once(tmp_path: Path) -> None:
    (tmp_path / ".stress_stack" / "hygiene").mkdir(parents=True)
    original = tmp_path / "ruff.toml"
    original.write_text('line-length = 79\n', encoding="utf-8")

    _write_configuration(tmp_path, "# Ruff configuration generated by stress-stack\n")
    backup = tmp_path / ".stress_stack" / "hygiene" / "ruff.toml.original"
    assert backup.read_text(encoding="utf-8") == "line-length = 79\n"

    _write_configuration(tmp_path, "# Ruff configuration generated by stress-stack\n# second\n")
    assert backup.read_text(encoding="utf-8") == "line-length = 79\n"
