from __future__ import annotations

from pathlib import Path

from stress_stack.locking import (
    compile_lock,
    count_packages,
    find_manifest,
    locked_packages,
    select_extras,
)

_LOCK = """\
# This file was autogenerated by uv via the following command:
#    uv pip compile setup.py --extra test
attrs==26.1.0 \\
    --hash=sha256:c647aa4a12dfbad9333ca4e71fe62ddc36f4e63b2d260a37a8b83d2f043ac309
    # via glom (setup.py)
boltons==26.1.0
    # via
    #   glom (setup.py)
    #   face
pyyaml==6.0.3
    # via glom (setup.py)
"""


def test_finds_manifest_in_precedence_order(tmp_path: Path) -> None:
    assert find_manifest(tmp_path) is None

    (tmp_path / "setup.py").write_text("", encoding="utf-8")
    assert find_manifest(tmp_path) == "setup.py"

    (tmp_path / "pyproject.toml").write_text("", encoding="utf-8")
    assert find_manifest(tmp_path) == "pyproject.toml"


def test_parses_pins_ignoring_hashes_and_annotations(tmp_path: Path) -> None:
    lockfile = tmp_path / "requirements.lock"
    lockfile.write_text(_LOCK, encoding="utf-8")

    assert locked_packages(lockfile) == {
        "attrs": "26.1.0",
        "boltons": "26.1.0",
        "pyyaml": "6.0.3",
    }
    assert count_packages(lockfile) == 3


def test_missing_lockfile_parses_as_empty(tmp_path: Path) -> None:
    assert locked_packages(tmp_path / "absent.lock") == {}
    assert count_packages(tmp_path / "absent.lock") == 0


def test_selects_the_conventional_test_extra() -> None:
    assert select_extras(["toml", "yaml", "test"]) == ["test"]
    assert select_extras(["Dev", "docs"]) == ["Dev"]
    assert select_extras(["docs", "toml"]) == []
    assert select_extras([]) == []


def test_repository_without_a_manifest_is_skipped_not_failed(tmp_path: Path) -> None:
    result = compile_lock(tmp_path, tmp_path / "requirements.lock")

    assert result.status == "skipped"
    assert result.reason == "no_dependency_manifest_found"
    assert result.lockfile is None
