from __future__ import annotations

import json
import tomllib
from pathlib import Path

from stress_stack.hygiene import (
    _baseline_configuration,
    _declared_extras,
    _rule_counts,
    _write_configuration,
)


def write_report(path: Path, root: Path, extras: list[str] | None) -> None:
    metadata: dict[str, object] = {"name": "example"}
    if extras is not None:
        metadata["provides_extra"] = extras
    path.write_text(
        json.dumps(
            {
                "install": [
                    {
                        "download_info": {"url": "https://pypi.org/simple/attrs"},
                        "metadata": {"name": "attrs", "provides_extra": ["dev"]},
                    },
                    {
                        "download_info": {"url": root.resolve().as_uri()},
                        "metadata": metadata,
                    },
                ]
            }
        ),
        encoding="utf-8",
    )


def test_declared_extras_reads_the_local_project_not_dependencies(tmp_path: Path) -> None:
    report = tmp_path / "report.json"
    write_report(report, tmp_path, ["toml", "yaml", "test"])

    assert _declared_extras(report, tmp_path) == ["toml", "yaml", "test"]


def test_declared_extras_handles_missing_and_malformed_reports(tmp_path: Path) -> None:
    assert _declared_extras(tmp_path / "absent.json", tmp_path) == []

    broken = tmp_path / "broken.json"
    broken.write_text("{not json", encoding="utf-8")
    assert _declared_extras(broken, tmp_path) == []

    without = tmp_path / "without.json"
    write_report(without, tmp_path, None)
    assert _declared_extras(without, tmp_path) == []


def test_baseline_configuration_is_valid_toml_with_every_residual_rule() -> None:
    content = _baseline_configuration(
        {"F401": 57, "E731": 19, "E722": 2},
        {"F401": "unused-import", "E731": "lambda-assignment"},
        78,
    )
    parsed = tomllib.loads(content)

    assert parsed["lint"]["ignore"] == ["E722", "E731", "F401"]
    assert parsed["extend-exclude"] == [".stress_stack"]


def test_baseline_configuration_records_count_date_and_rationale() -> None:
    content = _baseline_configuration({"F401": 57}, {"F401": "unused-import"}, 57)

    assert "Baseline adopted 20" in content
    assert "57 violation(s) across 1 rule(s)" in content
    assert "unsafe" in content.lower()
    assert "#   F401      57  unused-import" in content


def test_empty_residual_produces_empty_ignore_list() -> None:
    content = _baseline_configuration({}, {}, 0)
    assert tomllib.loads(content)["lint"]["ignore"] == []


def test_rule_counts_ignores_malformed_entries() -> None:
    counts = _rule_counts(
        [{"code": "F401"}, {"code": "F401"}, {"code": None}, {}, {"code": "E731"}]
    )
    assert counts == {"F401": 2, "E731": 1}


def test_existing_configuration_is_backed_up_once(tmp_path: Path) -> None:
    (tmp_path / ".stress_stack" / "hygiene").mkdir(parents=True)
    original = tmp_path / "ruff.toml"
    original.write_text('line-length = 79\n', encoding="utf-8")

    _write_configuration(tmp_path, "# Ruff configuration generated by stress-stack\n")
    backup = tmp_path / ".stress_stack" / "hygiene" / "ruff.toml.original"
    assert backup.read_text(encoding="utf-8") == "line-length = 79\n"

    _write_configuration(tmp_path, "# Ruff configuration generated by stress-stack\n# second\n")
    assert backup.read_text(encoding="utf-8") == "line-length = 79\n"


# --------------------------------------------------------------------------
# Provisioning is called seven times per run; only the first has work to do
# --------------------------------------------------------------------------


def _venv(monkeypatch, environment_root: Path, calls: list[list[str]]):
    """A provisioning run with the network parts replaced by a call counter."""
    from stress_stack import hygiene

    python = environment_root / "bin" / "python"
    python.parent.mkdir(parents=True, exist_ok=True)
    python.write_text("", encoding="utf-8")
    (environment_root / "pyvenv.cfg").write_text("home = /usr\n", encoding="utf-8")

    class _Ok:
        ok = True

        def failure_detail(self) -> str:
            return ""

    def fake_install(python_path, packages, **kwargs):
        calls.append(list(packages))
        return _Ok()

    monkeypatch.setattr(hygiene, "ensure_environment", lambda root: python)
    monkeypatch.setattr(hygiene, "install", fake_install)
    monkeypatch.setattr(hygiene, "_declared_extras", lambda report, root: [])
    monkeypatch.setattr(hygiene, "_declared_requirements", lambda report, root: [])
    monkeypatch.setattr(hygiene, "_requirements_by_extra", lambda report, root: {})
    monkeypatch.setattr(hygiene, "_local_install_entry", lambda report, root: {"metadata": {}})


def test_provisioning_is_skipped_when_the_stamp_matches(tmp_path: Path, monkeypatch) -> None:
    """Six of the seven calls per run re-resolved the whole dependency set."""
    from stress_stack.hygiene import provision_test_environment

    root = tmp_path / "repo"
    root.mkdir()
    (root / "pyproject.toml").write_text('[project]\nname = "app"\n', encoding="utf-8")
    environment_root = tmp_path / "tools"
    calls: list[list[str]] = []
    _venv(monkeypatch, environment_root, calls)

    first = provision_test_environment(root, environment_root)
    installs_after_first = len(calls)
    second = provision_test_environment(root, environment_root)

    assert installs_after_first > 0
    assert len(calls) == installs_after_first, "the second call reinstalled"
    assert second == first


def test_a_changed_manifest_reprovisions(tmp_path: Path, monkeypatch) -> None:
    from stress_stack.hygiene import provision_test_environment

    root = tmp_path / "repo"
    root.mkdir()
    manifest = root / "pyproject.toml"
    manifest.write_text('[project]\nname = "app"\n', encoding="utf-8")
    environment_root = tmp_path / "tools"
    calls: list[list[str]] = []
    _venv(monkeypatch, environment_root, calls)

    provision_test_environment(root, environment_root)
    before = len(calls)
    manifest.write_text('[project]\nname = "app"\ndependencies = ["attrs"]\n', encoding="utf-8")
    provision_test_environment(root, environment_root)

    assert len(calls) > before


def test_editing_a_source_file_does_not_reprovision(tmp_path: Path, monkeypatch) -> None:
    """testgen writes new test files mid-run; that must not cost a reinstall.

    Safe because every runtime path puts the source tree on PYTHONPATH ahead of
    site-packages, so the installed copy is not what gets measured anyway.
    """
    from stress_stack.hygiene import provision_test_environment

    root = tmp_path / "repo"
    (root / "tests").mkdir(parents=True)
    (root / "pyproject.toml").write_text('[project]\nname = "app"\n', encoding="utf-8")
    environment_root = tmp_path / "tools"
    calls: list[list[str]] = []
    _venv(monkeypatch, environment_root, calls)

    provision_test_environment(root, environment_root)
    before = len(calls)
    (root / "tests" / "test_generated.py").write_text("def test_x():\n    pass\n", encoding="utf-8")
    provision_test_environment(root, environment_root)

    assert len(calls) == before


def test_force_reprovisions_an_unchanged_tree(tmp_path: Path, monkeypatch) -> None:
    from stress_stack.hygiene import provision_test_environment

    root = tmp_path / "repo"
    root.mkdir()
    (root / "pyproject.toml").write_text('[project]\nname = "app"\n', encoding="utf-8")
    environment_root = tmp_path / "tools"
    calls: list[list[str]] = []
    _venv(monkeypatch, environment_root, calls)

    provision_test_environment(root, environment_root)
    before = len(calls)
    provision_test_environment(root, environment_root, force=True)

    assert len(calls) > before


def test_a_failed_provision_is_not_stamped(tmp_path: Path, monkeypatch) -> None:
    """A broken environment must be retried, not remembered."""
    from stress_stack import hygiene
    from stress_stack.hygiene import provision_test_environment

    root = tmp_path / "repo"
    root.mkdir()
    (root / "pyproject.toml").write_text('[project]\nname = "app"\n', encoding="utf-8")
    environment_root = tmp_path / "tools"
    calls: list[list[str]] = []
    _venv(monkeypatch, environment_root, calls)

    class _Broken:
        ok = False

        def failure_detail(self) -> str:
            return "no network"

    monkeypatch.setattr(hygiene, "install", lambda p, pkgs, **k: (calls.append(pkgs), _Broken())[1])

    record = provision_test_environment(root, environment_root)
    assert record["installed"] is False
    assert not (environment_root / "provision_stamp.json").exists()
