from __future__ import annotations

from stress_stack.container import (
    compare_to_baseline,
    detect_missing_system_library,
    render_dockerfile,
    select_python_version,
)
from stress_stack.graph import _container_status


def test_python_version_follows_requires_python() -> None:
    assert select_python_version(">=3.12") == "3.12"
    assert select_python_version(">=3.8") == "3.12"
    assert select_python_version(">=3.8,<3.11") == "3.10"
    assert select_python_version("<3.10") == "3.9"
    assert select_python_version("==3.11") == "3.11"


def test_python_version_defaults_when_unspecified() -> None:
    """glom declares no python_requires at all, so a default is required."""
    assert select_python_version(None) == "3.12"
    assert select_python_version("") == "3.12"


def test_dockerfile_installs_lock_before_copying_source() -> None:
    content = render_dockerfile(
        "python@sha256:abc", has_lock=True, installable=True, test_command='["pytest"]'
    )
    lines = content.splitlines()
    lock_index = next(i for i, line in enumerate(lines) if "requirements.lock" in line)
    copy_index = next(i for i, line in enumerate(lines) if line == "COPY . .")

    assert lock_index < copy_index
    assert "--require-hashes" in content
    assert "RUN pip install --no-deps --no-build-isolation ." in content
    assert content.startswith("# Generated by stress-stack.")
    assert "apt-get install -y --no-install-recommends git less" in content


def test_dockerfile_omits_steps_that_do_not_apply() -> None:
    content = render_dockerfile(
        "python:3.12-slim", has_lock=False, installable=False, test_command='["pytest"]'
    )

    assert "requirements.lock" not in content
    assert "pip install --no-deps --no-build-isolation ." not in content
    assert "COPY . ." in content


def test_dockerfile_sets_determinism_environment() -> None:
    content = render_dockerfile(
        "python@sha256:abc", has_lock=True, installable=True, test_command='["pytest"]'
    )

    for variable in ("PYTHONHASHSEED=0", "PYTHONDONTWRITEBYTECODE=1", "PIP_NO_CACHE_DIR=1"):
        assert variable in content


def test_dockerfile_supplies_version_without_shipping_git_history() -> None:
    content = render_dockerfile(
        "python@sha256:abc",
        has_lock=True,
        installable=True,
        test_command='["pytest"]',
        project_name="demo-package",
        project_version="1.2.3.dev4",
    )

    assert "SETUPTOOLS_SCM_PRETEND_VERSION=1.2.3.dev4" in content
    assert "SETUPTOOLS_SCM_PRETEND_VERSION_FOR_DEMO_PACKAGE=1.2.3.dev4" in content


def test_baseline_comparison_distinguishes_failure_modes() -> None:
    baseline = {"a": "passed", "b": "passed", "c": "failed"}

    assert compare_to_baseline({"a": "passed", "b": "passed", "c": "failed"}, baseline) == "matches"
    assert compare_to_baseline({"a": "passed", "b": "failed", "c": "failed"}, baseline) == "differs"
    assert compare_to_baseline({}, baseline) == "container_produced_no_results"
    assert compare_to_baseline({"a": "passed"}, None) == "no_baseline"
    # A host test the container never ran is the real fault: something failed
    # to collect inside the image.
    assert (
        compare_to_baseline({"x": "passed", "y": "passed", "c": "failed"}, baseline)
        == "tests_missing_in_container"
    )
    assert compare_to_baseline({"a": "passed", "b": "passed", "c": "passed"}, baseline) == "matches"
    # Generated tests run before containerization and legitimately add ids. Every
    # baseline pass still passes, so the claim the baseline makes still holds.
    assert (
        compare_to_baseline(
            {"a": "passed", "b": "passed", "c": "failed", "generated": "passed"}, baseline
        )
        == "matches_with_additions"
    )
    # An addition never excuses a regression on an existing test.
    assert (
        compare_to_baseline(
            {"a": "passed", "b": "failed", "c": "failed", "generated": "passed"}, baseline
        )
        == "differs"
    )


def test_missing_system_library_is_named_or_admitted() -> None:
    log = "  lxml/etree.c:96:10: fatal error: libxml/xmlversion.h: No such file"
    assert detect_missing_system_library(log) == "libxml/xmlversion.h"

    opaque = "error: command '/usr/bin/gcc' failed with exit code 1"
    assert detect_missing_system_library(opaque) == "unknown_compiler_failure"

    assert detect_missing_system_library("Successfully built wheel") is None


def test_verified_requires_identical_all_green_runs() -> None:
    assert _container_status("built", True, "matches", True) == "verified"
    assert _container_status("built", True, "matches", False) == "tests_failed"


def test_a_regenerated_test_disappearing_is_not_a_broken_image() -> None:
    """testgen rewrites its own output between the baseline and the image.

    Only reachable on a re-run, where the tree still holds the previous run's
    generated files — which is exactly when it fired, and why a fresh clone
    never saw it.
    """
    from stress_stack.container import compare_to_baseline

    baseline = {
        "tests/test_real.py::test_a": "passed",
        "tests.stress_stack_generated.test_generated_2::test_old": "passed",
    }
    container = {
        "tests/test_real.py::test_a": "passed",
        "tests.stress_stack_generated.test_generated_2::test_new": "passed",
    }

    assert compare_to_baseline(container, baseline) == "matches_with_additions"


def test_a_real_test_disappearing_is_still_a_broken_image() -> None:
    """The check the baseline exists for must survive the exemption."""
    from stress_stack.container import compare_to_baseline

    baseline = {"tests/test_real.py::test_a": "passed", "tests/test_real.py::test_b": "passed"}
    container = {"tests/test_real.py::test_a": "passed"}

    assert compare_to_baseline(container, baseline) == "tests_missing_in_container"


def test_a_real_test_regressing_is_still_a_difference() -> None:
    from stress_stack.container import compare_to_baseline

    baseline = {"tests/test_real.py::test_a": "passed"}
    container = {"tests/test_real.py::test_a": "failed"}

    assert compare_to_baseline(container, baseline) == "differs"
